spring:
  application:
    name: report-generator

  datasource:
    url: jdbc:postgresql://localhost:5432/report_generator
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: report-generator-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: reportGenerated:com.runalitycs.report_generator.dto.ReportGeneratedEventDto

server:
  port: 8083

app:
  timezone: Europe/Paris

  kafka:
    topics:
      metrics-calculated: metrics.calculated
      reports-generated: reports.generated
      dlq: reports.dlq